services:
  otel-collector:
    container_name: otel-collector
    build:
      context: ./otel-collector
    ports:
      - "4318:4318"
    env_file:
      - ../../.env
    environment:
      - ELASTIC_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - ELASTIC_API_KEY=${OTEL_EXPORTER_OTLP_ENDPOINT_API_KEY}
    command: ["--config=/etc/otelcol/config.yaml", "--set=service.telemetry.logs.level=debug"]

  nginx:
    container_name: nginx-proxy
    build:
      context: ./nginx
    image: nginx:latest
    ports:
      - "8123:8123"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - otel-collector

volumes:
  dev-elasticsearch:
  dev-kibana:
